cc := clang++
ccflags := -std=c++20 -O3 -flto 
lflags := -lgtest -lgtest_main -lpthread -flto
src := ../../src/graph.cpp
obj := $(patsubst %.cpp, %.o, $(wildcard *.cpp))
rm := rm -f

test: $(obj)
	$(cc) -o test $(obj) graph.o $(lflags) 
	
%.o:  %.cpp 
	$(cc) -c $< $(src) $(ccflags) 

clean: 
	$(rm) *.o
