#pragma once
#include <vector>
#include <map>
#include <unordered_map>
#include <unordered_set>

class GraphSet
{
	using nodeListTy = std::vector<int>;
	using setTy = std::unordered_map<int, nodeListTy>;

	struct nodeInfo 
	{
		// each vertex in adjSet indicates the 2nd vertex of the edge
		// i ---- j   means graph[i].adjSet contains j
		std::unordered_set<int> adjSet; 
	};

public:
	GraphSet ();

	GraphSet (const GraphSet&) = delete;
	GraphSet (GraphSet&&) = default;

	GraphSet& operator=(const GraphSet&) = delete;
	GraphSet& operator=(GraphSet&&) = default;

	~GraphSet() = default;

	// add a new edge btw n1 and n2 
	// if one of the nodes is not present, it will be inserted
	void addEdge(int n1, int n2);

	// create a random undirected and connected graph
	// number of nodes = numNodes
	// edges are generated by sampling a number p from a uniform distribution btw 0-1
	// if p is less than q than the edges is added
	// q defines the density of the graph
	void randomPopulate(int numNodes, float q);

	// compute the monotonely adjacent set for each node
	// return a map containing all the info
	setTy computeMonAdjSet() const;

	// compute the monotonely adjacent set for the specified node n
	nodeListTy computeMonAdjSet(int n) const;

	void setOrder(nodeListTy order);

	void reset();

	void printGraph() const;

	// ------------------------------------------------------------------------------------ 

	int getNodeNumber() const;

	int getEdgeNumber() const;

	nodeListTy getNodeList() const;

	// get the vertex based on the order (this is a) 
	int getVertex(int orderIdx) const;

	// get the order based on the vertex (this is a^-1) 
	int getOrder(int vertex) const;

	// get entire order list 
	nodeListTy getOrder() const;

	// get the adjacent list of node n
	nodeListTy getAdjSet(int n) const;

private: 
	// the index of the vector is the node number
	using graphTy = std::vector<nodeInfo>;

	int numEdges;
	// actual graph
	graphTy graph;
	// mapping btw internal node reprentation and user defined nodes
	std::unordered_map<int, int> nodeMapping;
	// alpha
	nodeListTy order;
	// alpha^-1
	nodeListTy inverseOrder;

	// ------------------ private methods ------------------
	
	float uniformProb();
};

